# Generated by Django 2.1.5 on 2019-01-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha ultima actualizacion')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-created'],
            },
        ),
    ]
