# Generated by Django 2.1.5 on 2019-01-24 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('publicacion', models.DateTimeField(default=datetime.datetime(2019, 1, 24, 17, 27, 20, 186467, tzinfo=utc), verbose_name='Fecha de publicacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Imagen')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha ultima actualizacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categorias', models.ManyToManyField(related_name='obtener_posts', to='blog.Categoria', verbose_name='Categorias')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Foro')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
