# Generated by Django 2.1.5 on 2019-01-24 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 18, 20, 56, 59219, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='foro',
            name='numero_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 18, 20, 56, 58223, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
