# Generated by Django 2.1.5 on 2019-01-24 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190124_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='numero_posts',
        ),
        migrations.AddField(
            model_name='foro',
            name='numeroPosts',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 18, 52, 23, 566105, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 18, 52, 23, 565110, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
