# Generated by Django 2.1.5 on 2019-01-24 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190124_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='numeroPosts',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 20, 30, 35, 219112, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 20, 30, 35, 217117, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
