# Generated by Django 2.1.5 on 2019-02-06 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20190206_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 18, 39, 51, 362099, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 18, 39, 51, 360133, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
