# Generated by Django 2.1.5 on 2019-02-07 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20190206_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 18, 4, 8, 361252, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 18, 4, 8, 360255, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
