# Generated by Django 2.1.5 on 2019-02-08 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20190208_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 16, 37, 43, 765515, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 16, 37, 43, 749894, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
