# Generated by Django 2.1.5 on 2019-02-16 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20190211_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 13, 17, 24, 60585, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 13, 17, 24, 57318, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
