# Generated by Django 2.1.5 on 2019-01-30 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('distancia', models.CharField(max_length=10)),
                ('plazas', models.CharField(max_length=5)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha ultima actualizacion')),
            ],
            options={
                'verbose_name': 'carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha ultima actualizacion')),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corredorEntreno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrenos',
                'ordering': ['corredor'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=2)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha ultima actualizacion')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.Carrera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'posiciones',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='participante',
            field=models.ManyToManyField(through='carreras.Posicion', to=settings.AUTH_USER_MODEL),
        ),
    ]
