# Generated by Django 2.1.5 on 2019-01-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreno',
            name='imagen',
            field=models.ImageField(default='hola', upload_to='carreras', verbose_name='Imagen'),
        ),
    ]
