# Generated by Django 2.1.5 on 2019-02-04 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_auto_20190204_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
