# Generated by Django 2.1.5 on 2019-02-04 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0004_carrera_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
