# Generated by Django 2.1.5 on 2019-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0007_auto_20190204_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='posicion',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
